# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               FrogHat LLC
tagline:             'An iOS Dev Shop'
description:         'FrogHat LLC is a software company specializing in small scale iOS projects, specifically games.'
url:                 http://froghat.github.io
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Ian Hanken
  url:               https://github.com/froghat
  email:             ian.hanken@froghat.org

# Custom vars
version:             1.0.0
